import { createClient } from "@sanity/client";
import { createGroqBuilder, makeSafeQueryRunner } from 'groqd';

// 👇 Import Sanity types, generated by your Sanity project.
import type * as SanityTypes from "../../../sanity.types.ts";

const sanityClient = createClient({
  projectId: 'edrheg39',
  dataset: 'production',
  apiVersion: '2025-06-06',
  useCdn: true,
});

// 👇 Create a type-safe query runner
export const runQuery = makeSafeQueryRunner((query) => sanityClient.fetch(query));

// 👇 Create a type-safe query builder
type SchemaConfig = {
  schemaTypes: SanityTypes.AllSanitySchemaTypes
  referenceSymbol: typeof SanityTypes.internalGroqTypeReferenceTo;
};
export const q = createGroqBuilder<SchemaConfig>({});
